services:
  gunicorn_project:
    image: docker.io/andylytical/jiracmdline
    environment:
      - JIRA_PROJECT
      - JIRA_SERVER
    volumes:
      - type: bind
        source: ${HOME}/.netrc
        target: /root/.netrc
      - type: volume
        source: static_web_files
        target: /mnt/static_web_files

  nginx:
    image: docker.io/andylytical/nginx-as-gunicorn-proxy
    ports:
      - "8080:80"
    depends_on:
      - gunicorn_project
    volumes:
      - type: volume
        source: static_web_files
        target: /mnt/static_web_files
volumes:
  static_web_files:
